### ISSUE TITLE
Slash Command

### ISSUE THREAD

**Issue by Aeris1One** [SkyCraft78/DiSky#10]
```
[16:03:55] [Server thread/INFO]: [Skript] Reloading dandelion.sk...
[16:03:55] [Server thread/WARN]: [DiSky] The bot named 'Dandelion' is already loaded on the server! Shutdown it or change the name.
[16:03:55] [Server thread/WARN]: [DiSky] A Slash Command just has been requested to Discord. Don't forget it can take an hour to be updated!
[16:03:55] [Server thread/ERROR]: #!#!
[16:03:55] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[16:03:55] [Server thread/ERROR]: #!#!
[16:03:55] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[16:03:55] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[16:03:55] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[16:03:55] [Server thread/ERROR]: #!#! SkQuery v4.1.4 DiSky v1.5.1 (https://disky.itsthesky.info/) Skent v3.0.0
[16:03:55] [Server thread/ERROR]: #!#! Here is full list of them:
[16:03:55] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[16:03:55] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[16:03:55] [Server thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[16:03:55] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[16:03:55] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[16:03:55] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[16:03:55] [Server thread/ERROR]: #!#!
[16:03:55] [Server thread/ERROR]: #!#! Stack trace:
[16:03:55] [Server thread/ERROR]: #!#! java.util.concurrent.RejectedExecutionException: The Requester has been stopped! No new requests can be requested!
[16:03:55] [Server thread/ERROR]: #!#! at net.dv8tion.jda.internal.requests.Requester.request(Requester.java:106)
[16:03:55] [Server thread/ERROR]: #!#! at net.dv8tion.jda.internal.requests.RestActionImpl.queue(RestActionImpl.java:197)
[16:03:55] [Server thread/ERROR]: #!#! at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:573)
[16:03:55] [Server thread/ERROR]: #!#! at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:539)
[16:03:55] [Server thread/ERROR]: #!#! at info.itsthesky.DiSky.skript.scope.commands.EffCreateCommand.execute(EffCreateCommand.java:63)
[16:03:55] [Server thread/ERROR]: #!#! at ch.njol.skript.lang.Effect.run(Effect.java:51)
[16:03:55] [Server thread/ERROR]: #!#! at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60)
[16:03:55] [Server thread/ERROR]: #!#! at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[16:03:55] [Server thread/ERROR]: #!#! at ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[16:03:55] [Server thread/ERROR]: #!#! at ch.njol.skript.events.EvtScript.register(EvtScript.java:60)
[16:03:55] [Server thread/ERROR]: #!#! at ch.njol.skript.ScriptLoader$4.call(ScriptLoader.java:737)
[16:03:55] [Server thread/ERROR]: #!#! at ch.njol.skript.ScriptLoader$4.call(ScriptLoader.java:1)
[16:03:55] [Server thread/ERROR]: #!#! at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:760)
[16:03:55] [Server thread/ERROR]: #!#! at ch.njol.skript.ScriptLoader.lambda$4(ScriptLoader.java:401)
[16:03:55] [Server thread/ERROR]: #!#! at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:420)
[16:03:55] [Server thread/ERROR]: #!#! at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:464)
[16:03:55] [Server thread/ERROR]: #!#! at ch.njol.skript.ScriptLoader.reloadScript(ScriptLoader.java:976)
[16:03:55] [Server thread/ERROR]: #!#! at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:185)
[16:03:55] [Server thread/ERROR]: #!#! at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[16:03:55] [Server thread/ERROR]: #!#! at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[16:03:55] [Server thread/ERROR]: #!#! at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:762)
[16:03:55] [Server thread/ERROR]: #!#! at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:747)
[16:03:55] [Server thread/ERROR]: #!#! at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:426)
[16:03:55] [Server thread/ERROR]: #!#! at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:395)
[16:03:55] [Server thread/ERROR]: #!#! at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1117)
[16:03:55] [Server thread/ERROR]: #!#! at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:956)
[16:03:55] [Server thread/ERROR]: #!#! at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273)
[16:03:55] [Server thread/ERROR]: #!#! at java.base/java.lang.Thread.run(Thread.java:834)
[16:03:55] [Server thread/ERROR]: #!#!
[16:03:55] [Server thread/ERROR]: #!#! Version Information:
[16:03:55] [Server thread/ERROR]: #!#! Skript: 2.5.3 (latest)
[16:03:55] [Server thread/ERROR]: #!#! Flavor: skriptlang-github
[16:03:55] [Server thread/ERROR]: #!#! Date: 2020-12-11
[16:03:55] [Server thread/ERROR]: #!#! Bukkit: 1.16.5-R0.1-SNAPSHOT
[16:03:55] [Server thread/ERROR]: #!#! Minecraft: 1.16.5
[16:03:55] [Server thread/ERROR]: #!#! Java: 11.0.10 (OpenJDK 64-Bit Server VM 11.0.10+9-Ubuntu-0ubuntu1.20.04)
[16:03:55] [Server thread/ERROR]: #!#! OS: Linux aarch64 5.4.0-1032-raspi
[16:03:55] [Server thread/ERROR]: #!#!
[16:03:55] [Server thread/ERROR]: #!#! Server platform: Spigot
[16:03:55] [Server thread/ERROR]: #!#!
[16:03:55] [Server thread/ERROR]: #!#! Current node: null
[16:03:55] [Server thread/ERROR]: #!#! Current item: create command using builder the last slash command builder with bot "Dandelion"
[16:03:55] [Server thread/ERROR]: #!#! Current trigger: load (script load) (dandelion.sk, line 7)
[16:03:55] [Server thread/ERROR]: #!#!
[16:03:55] [Server thread/ERROR]: #!#! Thread: Server thread
[16:03:55] [Server thread/ERROR]: #!#!
[16:03:55] [Server thread/ERROR]: #!#! Language: english
[16:03:55] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[16:03:55] [Server thread/ERROR]: #!#!
[16:03:55] [Server thread/ERROR]: #!#! End of Error.
[16:03:55] [Server thread/ERROR]: #!#!
```

Mon code : 
```
on load:
	login to "%{dandelion.discord.token}%" with name "Dandelion"
	change status of bot "Dandelion" to online
	mark the bot named "Dandelion" playing "%{dandelion.map.name}%"
	make new command:
    		set discord name of command to "map"
    		set description of command to "Obtenir la description de la map actuellement en jeu"
	create slash command with bot named "Dandelion"
	
on slash command:
  set {_m} to new message builder
  append "Voici quelques informations sur le serveur :" to builder {_m}
  append "%nl%`•` Nom de la map: %{dandelion.map.name}%" to builder {_m}
  append "%nl%`•` Auteur de la map: %{dandelion.map.author}%" to builder {_m}
  append "%nl%`•` Vue dans l'édition %{dandelion.map.edition}%" to builder {_m}
  append "%nl%`•` Rejoignez-nous sur `[REDACTED]`" to builder {_m}
  reply with {_m}
```

__**Informations du serveur**__
*Serveur*: 
- 3036-Spigot-a25e8ed-c85efa8 (MC: 1.16.5)

*Skript*: 
- 2.5.3

*Addons*: 
- Skent v3.0.0
- DiSky v1.5.1
- SkQuery v4.1.4

**Comment by Aeris1One** [comment]
Was due to intents not being enabled in Discord Developers panel
