### ISSUE TITLE
[BUG] DiSky can't reply to DM (NPE)

### ISSUE THREAD

**Issue by LvXP0** [SkyCraft78/DiSky#60]
**Name:** `DiSky can't reply to DM`
**Versions:** `1.13`

**Syntaxes affected:**
discord command test:
    trigger:
        reply with "test" -> NPE

**In-depth description of the bug:**
```
[16:47:35] [Server thread/WARN]: java.lang.NullPointerException
[16:47:35] [Server thread/WARN]: 	at info.itsthesky.disky.skript.effects.messages.EffReplyWith.lambda$walk$2(EffReplyWith.java:118)
[16:47:35] [Server thread/WARN]: 	at info.itsthesky.disky.tools.DiSkyErrorHandler.executeHandleCode(DiSkyErrorHandler.java:19)
[16:47:35] [Server thread/WARN]: 	at info.itsthesky.disky.skript.effects.messages.EffReplyWith.walk(EffReplyWith.java:96)
[16:47:35] [Server thread/WARN]: 	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[16:47:35] [Server thread/WARN]: 	at ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[16:47:35] [Server thread/WARN]: 	at info.itsthesky.disky.skript.commands.CommandObject.lambda$execute$2(CommandObject.java:102)
[16:47:35] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[16:47:35] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[16:47:35] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1502)
[16:47:35] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:434)
[16:47:35] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1415)
[16:47:35] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1141)
[16:47:35] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292)
[16:47:35] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[16:47:35] [Server thread/WARN]: [DiSky] DiSky tried to do an action on Discord, but got a NullPointerException! Check if all your value are set!
```

When I down version to 1.12, It works perfectly.

**Comment by SkyCraft78** [comment]
Fixed in 2.0, thanks you 😄
